# Jekyll Configuration for csidewalks.github.io
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#
# Site
#
baseurl: ""
url: "https://csidewalks.github.io"

#
# Blog
#
title: CSide Walks
email: csidewalks@mailinator.net
description: Blog about OScript and other OpenText Content Server development topics.

permalink: /posts/:year/:month/:day/:title/

#
# Social Accounts
#

github_username:  csidewalks

# Markdown Engine
markdown: kramdown
